### ISSUE TITLE
Restore RoadMap behavior

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#75]
The RoadMap box is the only one that has not been refactored yet, so I disabled it because the interfaces it uses have changed.
- [x] For search view
- [ ] For bike view
- [ ] For stands view
